### ISSUE TITLE
Error when installing on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by hemmingstein** [hyperopt/hyperopt-sklearn#127]
I'm using `python 3.6.5` (anaconda) and `pip 19.0.1` - when trying to install hyperopt-sklearn via
`pip install -e . ` I get the following message:

> Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/oego/Software/hyperopt-sklearn/setup.py", line 24, in <module>
>         long_description = open('README.md').read(),
>       File "/home/oego/Software/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1807: ordinal not in range(128)
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /home/oego/Software/hyperopt-sklearn/

I searched for the error message on the web and already installed libevent-dev and python-dev since it solved this issue for other people, but I still get this error message.

Any thoughts on this?

**Comment by yiyang-yu** [comment]
Hi, I am having same issue. Any updates?
