### ISSUE TITLE
estimator.fit crashes for sparse data in spite of using any_sparse_classifier()

### ISSUE THREAD

**Issue by eldor4do** [hyperopt/hyperopt-sklearn#43]
I am trying to optimize for a text classification problem. For pre-processing I used sckit's CountVectorizer and TFIDF to get a sparse matrix as my data set.  I am trying to optimize using any_sparse_classifier() method like,
```
    # Preprocessing
    X_train_counts = count_vect.fit_transform(train)
    X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

    X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, target, test_size=0.3, random_state=42)

    # Optimizing
    from hpsklearn import HyperoptEstimator, any_sparse_classifier
    from hyperopt import tpe


    estim = HyperoptEstimator( classifier=any_sparse_classifier('myclf') ,
                            algo=tpe.suggest, trial_timeout=300, verbose=1)

    estim.fit(X_train, y_train)

    print(estim.score(X_test, y_test))
    # <<show score here>>
    print( estim.best_model() )
    # <<show model here>>
```

However it runs for a couple of iterations, but then crashes, each time giving a different error.
These are some of the trace backs I have received:

1.
```
Fitting Normalizer(copy=True, norm='l1') to X of shape (30536, 252461)
Transforming fit and Xval (30536, 252461) (7635, 252461)
Training classifier SVC(C=1909.81396385, cache_size=1000.0, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=160507086, probability=False, random_state=4, shrinking=False,
  tol=0.0107899097808, verbose=False) on X of dimension (30536, 252461)
Scoring on Xval of shape (7635, 252461)
OK trial with accuracy 98.7 +- 0.1
Traceback (most recent call last):
  File "/home/ubuntu/train.py", line 273, in trainclassifier
    estim.fit(X_train, y_train)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/estimator.py", line 384, in fit
    fit_iter.send(increment)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/estimator.py", line 353, in fit_iter
    return_argmin=False, # -- in case no success so far
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 306, in fmin
    return_argmin=return_argmin,
  File "/home/ubuntu/hyperopt/hyperopt/base.py", line 633, in fmin
    return_argmin=return_argmin)
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 319, in fmin
    rval.exhaust()
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 198, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 172, in run
    self.serial_evaluate()
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 89, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/ubuntu/hyperopt/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/estimator.py", line 322, in fn_with_timeout
    raise fn_rval[1]
TypeError: MinMaxScaler does no support sparse input. You may consider to use MaxAbsScaler instead.
Fitting MinMaxScaler(copy=True, feature_range=(-1.0, 1.0)) to X of shape (30536, 252461) 
```

2.
```
Training classifier KNeighborsClassifier(algorithm='auto', leaf_size=41, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=40, p=2,
           weights='distance') on X of dimension (30536, 252461)
Scoring on Xval of shape (7635, 252461)
OK trial with accuracy 96.7 +- 0.2
Traceback (most recent call last):
  File "/home/ubuntu/train.py", line 273, in trainclassifier
    estim.fit(X_train, y_train)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/estimator.py", line 384, in fit
    fit_iter.send(increment)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/estimator.py", line 353, in fit_iter
    return_argmin=False, # -- in case no success so far
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 306, in fmin
    return_argmin=return_argmin,
  File "/home/ubuntu/hyperopt/hyperopt/base.py", line 633, in fmin
    return_argmin=return_argmin)
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 319, in fmin
    rval.exhaust()
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 198, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 172, in run
    self.serial_evaluate()
  File "/home/ubuntu/hyperopt/hyperopt/fmin.py", line 89, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/ubuntu/hyperopt/hyperopt/base.py", line 837, in evaluate
    print_node_on_error=self.rec_eval_print_node_on_error)
  File "/home/ubuntu/hyperopt/hyperopt/pyll/base.py", line 912, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/home/ubuntu/hyperopt-sklearn/hpsklearn/components.py", line 20, in sklearn_SVC
    return sklearn.svm.SVC(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/classes.py", line 539, in __init__
    random_state=random_state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 507, in __init__
    random_state=random_state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 86, in __init__
    raise ValueError(msg)
ValueError: The gamma value of 0.0 is invalid. Use 'auto' to set gamma to a value of 1 / n_features.
```

What is the issue here?

**Comment by bjkomer** [comment]
It looks like if you don't explicitly tell the HyperoptEstimator to use no preprocessing (via preprocessing=[]) it will use any_preprocessing() by default, and one of the options included in the list does not work for sparse data. This is a bug that should get fixed. I think it may also be more intuitive if the default was no preprocessing.

The second error is due to a change in sklearns API for SVC in the most recent version. I'll get the fix for that in once I have access to a computer later today.

**Comment by bjkomer** [comment]
The pull request #41 includes a fix for the second error (along with many other features), so hopefully that gets merged in soon. In the meantime you could use the branch from that pull request directly, or alternatively the branch from #40 which is just a fix for the error. The latter pull request will likely be cancelled in favour of the more comprehensive one.

Let me know if you are still having issues or if anything is unclear.

**Comment by eldor4do** [comment]
Thanks! Will give that a try.
