### ISSUE TITLE
Error occured when replacing demo iris data with new dataset??

### ISSUE THREAD

**Issue by andyxzq** [hyperopt/hyperopt-sklearn#48]
I replace demo's iris data with my own data, but I got the error as follows:
Traceback (most recent call last):
  File "/opt/hyperopt-sklearn/hpsklearn/tests/test_demo.py", line 92, in <module>
    test_demo_yyb()
  File "/opt/hyperopt-sklearn/hpsklearn/tests/test_demo.py", line 82, in test_demo_yyb
    fit_iterator.send(1)  # -- try one more model
  File "/opt/hyperopt-sklearn/hpsklearn/estimator.py", line 348, in fit_iter
    max_evals=len(self.trials.trials) + increment
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 334, in fmin
    rval.exhaust()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 294, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 268, in run
    self.serial_evaluate()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 187, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 122, in evaluate
    dict_rval.keys())
**ValueError: ('dictionary must have "loss" key', ['status', 'failure'])**

**Comment by bjkomer** [comment]
My guess for what is happening is that one of the parameter combinations evaluated on your dataset is throwing an exception (timeout too short to complete, invalid parameters for the data, etc). Normally this should be fine and `hyperopt` can handle these cases, but I think you are running an older version of `hyperopt` that may not be able to (I noticed the line numbers given for `fmin.py` don't line up with what is on master).

One thing worth trying is to use the [latest version](https://github.com/hyperopt/hyperopt) of `hyperopt` from GitHub and see if that helps.

To figure out why a particular evalutation is failing, you can look at the value of the `'failure'` key of the trial in the `Trials` object. This will give you a string of the actual underlying exception or a message saying it timed out.

**Comment by andyxzq** [comment]
I follow your advice and update the latest version hyperopt，but I get the new error as follows:
Traceback (most recent call last):
  File "/opt/hyperopt-sklearn/hpsklearn/tests/test_demo.py", line 89, in <module>
    test_demo_yyb()
  File "/opt/hyperopt-sklearn/hpsklearn/tests/test_demo.py", line 79, in test_demo_yyb
    fit_iterator.send(1)  # -- try one more model
  File "/opt/hyperopt-sklearn/hpsklearn/estimator.py", line 348, in fit_iter
    max_evals=len(self.trials.trials) + increment
  File "build/bdist.linux-x86_64/egg/hyperopt/fmin.py", line 306, in fmin
  File "build/bdist.linux-x86_64/egg/hyperopt/base.py", line 633, in fmin
  File "build/bdist.linux-x86_64/egg/hyperopt/fmin.py", line 321, in fmin
  File "build/bdist.linux-x86_64/egg/hyperopt/base.py", line 588, in argmin
  File "build/bdist.linux-x86_64/egg/hyperopt/base.py", line 583, in best_trial
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1033, in argmin
    return _wrapit(a, 'argmin', axis, out)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
I use the same configuration with demo iris data and my own data only contains binary 0 and 1, I don't come across the error when using iris data, does it mean that my data cause the problem?

**Comment by bjkomer** [comment]
It seems like none of your trials are returning a loss value, so when it tries to find the lowest loss, it throws an error because the list is empty. This could be because your data is not working well with the type of classifiers being used. 

I'd suggest adding in a print statement to see what the cause of the failures are. Inside the `while` loop in the demo, put in as the first line `print(estimator.trials.results)` or `print(estimator.trials.results[-1])` to just print the latest result each time.

I suspect the issue might be the timeout not being long enough for your data (it's set to 15 seconds in the iris demo, which is really short for some classifiers and/or computers). If the print statement above returns something like `{'status': 'fail', 'failure': 'TimeOut'}` then this is the issue and you can try setting a longer `trial_timeout` in `HyperoptEstimator`.

**Comment by andyxzq** [comment]
Very thanks to your patient reply! 
From my experiment, I think the trails and timeout indeed influence each other. At some settings of these two parameters, I get the result, some others don't. 
I exclude all other models except GBDT, I really concern the effect with the parameter found by the hyperopt-sklearn, but I get very poor result with auc slightly larger than 0.5, so how can I do to get a better result?

**Comment by bjkomer** [comment]
There are a few options worth trying to improve results

1. Increase the number of trials (max_evals)
2. Improve the search space
3. Change the preprocessing 

Increasing the number of trials allows hyperopt to have more information to work with to try to find good parameter sets. The downside is it will take longer to run through all of those trials, so there is a tradeoff. It is possible to save previously run sets of trials (by saving and loading the `HyperoptEstimator` object) so that if you run your script again, it will always start where you left off. The newly added `warm_start` feature is helpful for this (the demo is set up slightly differently than the standard use case, so instead of using `warm_start` you'll want to set your `max_evals` to some large number, and then iterate through your loop that calls `fit_iterator` the desired number of times each run).

The default search space for GBDT may not be ideal for your dataset, so you may want to customize it. You can change the search space for any parameter, and if you know some parameters that work well, you can set them explicitly and let hyperopt only search through the other ones.
An example of fixing a parameter and changing the distribution of another parameter: 
```
estimator = HyperoptEstimator(classifier=gradient_boosting('my_classifier', 
                                                           loss='deviance', 
                                                           learning_rate=hp.lognormal('my_learning_rate', np.log(0.001), np.log(10))))
```

Preprocessing can often make a big difference in performance. By default hyperopt-sklearn will try a few preprocessing methods on your data using the `any_preprocessing` function, unless you explicitly tell it otherwise. If you already handle your own preprocessing and don't want hyperopt-sklearn to be trying extra things, you can set `preprocessing=[]` when constructing the `HyperoptEstimator`.

**Comment by bjkomer** [comment]
I'm not sure which paper you are referring to, but [this](https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf) paper describes both TPE and GP. Hopefully that will be helpful (specifically sections 3, 4, 7, and 8). James (@jaberg) developed the TPE approach, so he would know more about it than me.
