### ISSUE TITLE
Installation issue (Windows 64-bit)

### ISSUE THREAD

**Issue by nd26** [hyperopt/hyperopt-sklearn#81]
Hi there. I've installed hyperopt successfully but installation of hyperopt-sklearn comes with the following error:
(C:\Users\User\Anaconda3) C:\Users\User\Anaconda3\Lib\site-packages\hyperopt-sklearn-0.0.3\hyperopt-sklearn>pip install -e .
Obtaining file:///C:/Users/User/Anaconda3/Lib/site-packages/hyperopt-sklearn-0.0.3/hyperopt-sklearn
    Complete output from command python setup.py egg_info:
    Extracting in C:\Users\User\AppData\Local\Temp\tmpqb_pl0a6
    Traceback (most recent call last):
      File "c:\users\user\hyperopt\distribute_setup.py", line 150, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\Anaconda3\Lib\site-packages\hyperopt-sklearn-0.0.3\hyperopt-sklearn\setup.py", line 36, in <module>
        distribute_setup.use_setuptools()
      File "c:\users\user\hyperopt\distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "c:\users\user\hyperopt\distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "c:\users\user\hyperopt\distribute_setup.py", line 105, in _build_egg
        _extractall(tar)
      File "c:\users\user\hyperopt\distribute_setup.py", line 500, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\Anaconda3\Lib\site-packages\hyperopt-sklearn-0.0.3\hyperopt-sklearn\

I am using Anaconda as you can see and python 3.6. I've tried multiple things but I couldn't get past this error.

**Comment by geoblog** [comment]
maybe it should be able to install hpsklearn by pip install hpsklearn someday later.

**Comment by nd26** [comment]
@geoblog nope

**Comment by kevin-meng** [comment]
same problem happens 
i have already install the Numpy 1.13,  but hysklearn still  Collecting NumPy==1.11.0 (from hpsklearn==0.0.3)
and fail to install 
===========
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\python27\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "c:\python27\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 139, in iter
    for x in it:
  File "c:\python27\lib\site-packages\pip\download.py", line 560, in resp_read
    decode_content=False):
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 324, in read
    flush_decoder = True
  File "c:\python27\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ("Connection broken: error(10054, '')", error(10054, ''))
==================

**Comment by fingoldo** [comment]
Same problem. Any remedy, guys?
Really keen to try your package, please be more user-friendly )
