### ISSUE TITLE
Demo error when fitting the estimator

### ISSUE THREAD

**Issue by tsdalton** [hyperopt/hyperopt-sklearn#83]
Installed:
```
python 2.7.13
hyperopt 0.1
hpsklearn 0.0.3
```

I am getting an error when I attempt to run the example code

```
from hpsklearn import HyperoptEstimator, any_classifier, any_preprocessing
from sklearn.datasets import load_iris
from hyperopt import tpe
import numpy as np

iris = load_iris()

X = iris.data
y = iris.target

test_size = int(0.2 * len(y))
np.random.seed(13)
indices = np.random.permutation(len(X))
X_train = X[ indices[:-test_size]]
y_train = y[ indices[:-test_size]]
X_test = X[ indices[-test_size:]]
y_test = y[ indices[-test_size:]]


estim = HyperoptEstimator(classifier=any_classifier('my_clf'),
                          preprocessing=any_preprocessing('my_pre'),
                          algo=tpe.suggest,
                          max_evals=100,
                          trial_timeout=120)

estim.fit(X_train, y_train)
```
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hpsklearn/estimator.py", line 746, in fit
    fit_iter.send(increment)
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hpsklearn/estimator.py", line 657, in fit_iter
    return_argmin=False, # -- in case no success so far
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/Users/XXX/anaconda/envs/XXX/lib/python2.7/site-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object has no attribute '__getitem__'
```

Any thoughts?

**Comment by tsdalton** [comment]
It appears that the issue is with the `networkx` dependency. Running with `networkx==2.0` causes the error above but `networkx==1.11` seems fine.

**Comment by tsdalton** [comment]
I've opened up a PR with the appropriate fix. This should be considered a temporary fix until a new hyperopt pip package is released. See https://github.com/hyperopt/hyperopt/issues/318
