### ISSUE TITLE
Error when using cross-validation and an offline algorithm

### ISSUE THREAD

**Issue by lstmemery** [hyperopt/hyperopt-sklearn#92]
When I ran this code:

```
estim = HyperoptEstimator(classifier=sgd("SGD"),
                          algo=tpe.suggest,
                          loss_fn=f1_scorer,
                          max_evals=1,
                          trial_timeout=600,
                          verbose=False
                          )

estim.fit(training_features,
          training_target,
          n_folds=10)
```

I received this mysterious stacktrace: 

```
Traceback (most recent call last):
  File "/home/deadhead/Documents/imbellus-projects/imbellusRank/src/hpsklearn_test.py", line 42, in <module>
    n_folds=10)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hpsklearn/estimator.py", line 746, in fit
    fit_iter.send(increment)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hpsklearn/estimator.py", line 657, in fit_iter
    return_argmin=False, # -- in case no success so far
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/deadhead/miniconda3/envs/imbellusSupervised/lib/python3.6/site-packages/hpsklearn/estimator.py", line 620, in fn_with_timeout
    raise fn_rval[1]
TypeError: '>=' not supported between instances of 'NoneType' and 'NoneType'
```

It took a while, but I discovered that the bug is on line 317 of estimator.py. 

```
n_iters = None
```
Then on line 323:
```
cv_n_iters = np.append(cv_n_iters, n_iters)
```
This creates an array of all Nones. So on line 352:
```
'iterations': cv_n_iters.max(),
```
Throws the stacktrace error message.

My workaround was to change `n_iters = None` to `n_iters = 0` but I'm not sure how you would like to fix it.

I'd be willing to submit a PR about this.

**Comment by meenaparam** [comment]
I also had this problem - thanks for showing a solution. Did a PR go through for this?

**Comment by lstmemery** [comment]
I've made a fork that has this change and support for repeated cv: https://github.com/lstmemery/hyperopt-sklearn/tree/master/hpsklearn

**Comment by DuongVu39** [comment]
Can you check again in your folk? Instead of changing line 317 as suggested above, you only change line 14 and 19 of estimator.py and I still got the same error. 

Thank you.

**Comment by lstmemery** [comment]
Hmm, I'll have to check what's going on here. Thanks for bringing this to my attention
